baseURL = 'http://localhost:1313/'
languageCode = 'en-gb'
title = 'UKSFTA | Intelligence Portal'
theme = []

[params]
    classification = "SECRET // UK EYES ONLY"
    unitName = "UKSF TASKFORCE ALPHA"
    serviceName = "Common Operational Picture (COP)"
    supabaseUrl = "" # Will be injected by run_dev.sh
    supabaseServiceRoleKey = "" # Will be injected by run_dev.sh
